// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: biz.proto

package biz

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BizRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Param string `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
}

func (x *BizRequest) Reset() {
	*x = BizRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BizRequest) ProtoMessage() {}

func (x *BizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BizRequest.ProtoReflect.Descriptor instead.
func (*BizRequest) Descriptor() ([]byte, []int) {
	return file_biz_proto_rawDescGZIP(), []int{0}
}

func (x *BizRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BizRequest) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

type BizResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Errno   int32  `protobuf:"varint,2,opt,name=errno,proto3" json:"errno,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BizResponse) Reset() {
	*x = BizResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biz_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BizResponse) ProtoMessage() {}

func (x *BizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_biz_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BizResponse.ProtoReflect.Descriptor instead.
func (*BizResponse) Descriptor() ([]byte, []int) {
	return file_biz_proto_rawDescGZIP(), []int{1}
}

func (x *BizResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *BizResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *BizResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_biz_proto protoreflect.FileDescriptor

var file_biz_proto_rawDesc = []byte{
	0x0a, 0x09, 0x62, 0x69, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x62, 0x69, 0x7a,
	0x22, 0x36, 0x0a, 0x0a, 0x42, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x51, 0x0a, 0x0b, 0x42, 0x69, 0x7a, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6e,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x3c, 0x0a, 0x0a, 0x42,
	0x69, 0x7a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x42, 0x69, 0x7a, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x42, 0x69, 0x7a, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_biz_proto_rawDescOnce sync.Once
	file_biz_proto_rawDescData = file_biz_proto_rawDesc
)

func file_biz_proto_rawDescGZIP() []byte {
	file_biz_proto_rawDescOnce.Do(func() {
		file_biz_proto_rawDescData = protoimpl.X.CompressGZIP(file_biz_proto_rawDescData)
	})
	return file_biz_proto_rawDescData
}

var file_biz_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_biz_proto_goTypes = []interface{}{
	(*BizRequest)(nil),  // 0: biz.BizRequest
	(*BizResponse)(nil), // 1: biz.BizResponse
}
var file_biz_proto_depIdxs = []int32{
	0, // 0: biz.BizService.Execute:input_type -> biz.BizRequest
	1, // 1: biz.BizService.Execute:output_type -> biz.BizResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_biz_proto_init() }
func file_biz_proto_init() {
	if File_biz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_biz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BizRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biz_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BizResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_biz_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_biz_proto_goTypes,
		DependencyIndexes: file_biz_proto_depIdxs,
		MessageInfos:      file_biz_proto_msgTypes,
	}.Build()
	File_biz_proto = out.File
	file_biz_proto_rawDesc = nil
	file_biz_proto_goTypes = nil
	file_biz_proto_depIdxs = nil
}
